### ISSUE TITLE
hopla non instalable from conda

### ISSUE THREAD

**Issue by bruniix** [CenterForMedicalGeneticsGhent/Hopla#29]
First, to clarify, this is one of the first times I am using GitHub to ask a question, so I apologize if the procedure isn't correct.

These days, I have been trying (from two different computers) to install hopla. However, when proceeding through conda with
"conda install -c conda-forge -c bioconda hopla" or "conda install bioconda::hopla"

I receive the same message indicating that it isn't possible to proceed because there isn't a higher or equal version of bioconductor-DNAcopy.

Since I am not used to working with conda and bioconda packages, I'm not sure if it is possible to proceed or if it is an actual failure from somewhere.

Thanks.

![help conda](https://github.com/CenterForMedicalGeneticsGhent/Hopla/assets/152556934/e75959d4-cfcb-49f8-82a9-fd1f2d24b2c9)

**Comment by matthdsm** [comment]
You're trying to run hopla on windows, which is not compatible. 
Try again in WSL/MacOS or a dedicated Linux machine.

M
