### ISSUE TITLE
Parse sample id's from vcf header

### ISSUE THREAD

**Issue by matthdsm** [CenterForMedicalGeneticsGhent/Hopla#6]
clean up mandatory args

**Comment by matthdsm** [comment]
e.g. 
if no `--sample.id`;
    parse vcf samples;
else:
   only parse given samples

**Comment by leraman** [comment]
problem here:
- hopla can't run in 'multi sample mode' when no relations (`--mother`/`--father`) are given; hopla requires `--sample.id` to define these relations
- in 'single sample mode', hopla needs to know which sample of a possibly multi-sample vcf should be analyzed, therefore also requiring `--sample.id`.

when implementing a `--ped` functionality, `--sample.id` is of course no longer mandatory

**Comment by matthdsm** [comment]
same argument holds up, just add a check and error when args are missing

**Comment by leraman** [comment]
The 'default' of `--sample.ids` could be to only analyze the first sample in the vcf, thereby allowing single sample vcf file analyses without `--sample.ids`?
